name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Usa la versión de Python que prefieras

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Si tienes un archivo requirements.txt

    - name: Install pytest
      run: pip install pytest

    - name: Run tests with pytest
      run: |
        pytest tests  # Asegúrate de que las pruebas están en una carpeta llamada 'tests'
